version: '3.7'
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_SERVER=mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin

  ms-node-hexagonal-template:
    build: .
    image:  ms-node-hexagonal-template
    ports:
        - 3000:3000
    container_name: ms-node-hexagonal-template
    restart: always
    depends_on:
        - mongo
    environment:
        PORT: 3000
        MONGO_USER: admin
        MONGO_PASS: admin
        MONGO_HOST: mongo
        MONGO_PORT: 27017
        MONGO_DB_NAME: teste
